export const HACKATHON_SLUG = "hackathon-00";
export const USERNAME_REGEX = /^[a-z0-9][a-z0-9_-]{1,28}[a-z0-9]$/;
export const SLUG_REGEX = /^[a-z0-9]+(?:[-_][a-z0-9]+)*$/;
export const DISCORD_INVITE_URL = "https://discord.gg/buildstory";
export const X_URL = "https://x.com/buildstorycom";
export const TWITCH_URL = "https://twitch.tv/thecoppinger";
export const VOLUNTEER_URL = "#"; // TODO: replace with real URL
export const SPONSOR_URL = "/sponsor-apply";
export const SPONSOR_CREDITS_URL = "#"; // TODO: replace with real URL
export const DOCS_URL = "#"; // TODO: replace with real URL
export const SUBMISSION_DEADLINE = new Date("2026-03-11T00:00:00Z"); // March 10 EOD UTC
