export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", flag: "\u{1F1E6}\u{1F1EB}" },
  { code: "AL", name: "Albania", flag: "\u{1F1E6}\u{1F1F1}" },
  { code: "DZ", name: "Algeria", flag: "\u{1F1E9}\u{1F1FF}" },
  { code: "AS", name: "American Samoa", flag: "\u{1F1E6}\u{1F1F8}" },
  { code: "AD", name: "Andorra", flag: "\u{1F1E6}\u{1F1E9}" },
  { code: "AO", name: "Angola", flag: "\u{1F1E6}\u{1F1F4}" },
  { code: "AI", name: "Anguilla", flag: "\u{1F1E6}\u{1F1EE}" },
  { code: "AQ", name: "Antarctica", flag: "\u{1F1E6}\u{1F1F6}" },
  { code: "AG", name: "Antigua and Barbuda", flag: "\u{1F1E6}\u{1F1EC}" },
  { code: "AR", name: "Argentina", flag: "\u{1F1E6}\u{1F1F7}" },
  { code: "AM", name: "Armenia", flag: "\u{1F1E6}\u{1F1F2}" },
  { code: "AW", name: "Aruba", flag: "\u{1F1E6}\u{1F1FC}" },
  { code: "AU", name: "Australia", flag: "\u{1F1E6}\u{1F1FA}" },
  { code: "AT", name: "Austria", flag: "\u{1F1E6}\u{1F1F9}" },
  { code: "AZ", name: "Azerbaijan", flag: "\u{1F1E6}\u{1F1FF}" },
  { code: "BS", name: "Bahamas", flag: "\u{1F1E7}\u{1F1F8}" },
  { code: "BH", name: "Bahrain", flag: "\u{1F1E7}\u{1F1ED}" },
  { code: "BD", name: "Bangladesh", flag: "\u{1F1E7}\u{1F1E9}" },
  { code: "BB", name: "Barbados", flag: "\u{1F1E7}\u{1F1E7}" },
  { code: "BY", name: "Belarus", flag: "\u{1F1E7}\u{1F1FE}" },
  { code: "BE", name: "Belgium", flag: "\u{1F1E7}\u{1F1EA}" },
  { code: "BZ", name: "Belize", flag: "\u{1F1E7}\u{1F1FF}" },
  { code: "BJ", name: "Benin", flag: "\u{1F1E7}\u{1F1EF}" },
  { code: "BM", name: "Bermuda", flag: "\u{1F1E7}\u{1F1F2}" },
  { code: "BT", name: "Bhutan", flag: "\u{1F1E7}\u{1F1F9}" },
  { code: "BO", name: "Bolivia", flag: "\u{1F1E7}\u{1F1F4}" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "\u{1F1E7}\u{1F1E6}" },
  { code: "BW", name: "Botswana", flag: "\u{1F1E7}\u{1F1FC}" },
  { code: "BR", name: "Brazil", flag: "\u{1F1E7}\u{1F1F7}" },
  { code: "IO", name: "British Indian Ocean Territory", flag: "\u{1F1EE}\u{1F1F4}" },
  { code: "VG", name: "British Virgin Islands", flag: "\u{1F1FB}\u{1F1EC}" },
  { code: "BN", name: "Brunei", flag: "\u{1F1E7}\u{1F1F3}" },
  { code: "BG", name: "Bulgaria", flag: "\u{1F1E7}\u{1F1EC}" },
  { code: "BF", name: "Burkina Faso", flag: "\u{1F1E7}\u{1F1EB}" },
  { code: "BI", name: "Burundi", flag: "\u{1F1E7}\u{1F1EE}" },
  { code: "CV", name: "Cabo Verde", flag: "\u{1F1E8}\u{1F1FB}" },
  { code: "KH", name: "Cambodia", flag: "\u{1F1F0}\u{1F1ED}" },
  { code: "CM", name: "Cameroon", flag: "\u{1F1E8}\u{1F1F2}" },
  { code: "CA", name: "Canada", flag: "\u{1F1E8}\u{1F1E6}" },
  { code: "KY", name: "Cayman Islands", flag: "\u{1F1F0}\u{1F1FE}" },
  { code: "CF", name: "Central African Republic", flag: "\u{1F1E8}\u{1F1EB}" },
  { code: "TD", name: "Chad", flag: "\u{1F1F9}\u{1F1E9}" },
  { code: "CL", name: "Chile", flag: "\u{1F1E8}\u{1F1F1}" },
  { code: "CN", name: "China", flag: "\u{1F1E8}\u{1F1F3}" },
  { code: "CO", name: "Colombia", flag: "\u{1F1E8}\u{1F1F4}" },
  { code: "KM", name: "Comoros", flag: "\u{1F1F0}\u{1F1F2}" },
  { code: "CG", name: "Congo", flag: "\u{1F1E8}\u{1F1EC}" },
  { code: "CD", name: "Congo (DRC)", flag: "\u{1F1E8}\u{1F1E9}" },
  { code: "CK", name: "Cook Islands", flag: "\u{1F1E8}\u{1F1F0}" },
  { code: "CR", name: "Costa Rica", flag: "\u{1F1E8}\u{1F1F7}" },
  { code: "HR", name: "Croatia", flag: "\u{1F1ED}\u{1F1F7}" },
  { code: "CU", name: "Cuba", flag: "\u{1F1E8}\u{1F1FA}" },
  { code: "CW", name: "Curacao", flag: "\u{1F1E8}\u{1F1FC}" },
  { code: "CY", name: "Cyprus", flag: "\u{1F1E8}\u{1F1FE}" },
  { code: "CZ", name: "Czechia", flag: "\u{1F1E8}\u{1F1FF}" },
  { code: "CI", name: "Cote d'Ivoire", flag: "\u{1F1E8}\u{1F1EE}" },
  { code: "DK", name: "Denmark", flag: "\u{1F1E9}\u{1F1F0}" },
  { code: "DJ", name: "Djibouti", flag: "\u{1F1E9}\u{1F1EF}" },
  { code: "DM", name: "Dominica", flag: "\u{1F1E9}\u{1F1F2}" },
  { code: "DO", name: "Dominican Republic", flag: "\u{1F1E9}\u{1F1F4}" },
  { code: "EC", name: "Ecuador", flag: "\u{1F1EA}\u{1F1E8}" },
  { code: "EG", name: "Egypt", flag: "\u{1F1EA}\u{1F1EC}" },
  { code: "SV", name: "El Salvador", flag: "\u{1F1F8}\u{1F1FB}" },
  { code: "GQ", name: "Equatorial Guinea", flag: "\u{1F1EC}\u{1F1F6}" },
  { code: "ER", name: "Eritrea", flag: "\u{1F1EA}\u{1F1F7}" },
  { code: "EE", name: "Estonia", flag: "\u{1F1EA}\u{1F1EA}" },
  { code: "SZ", name: "Eswatini", flag: "\u{1F1F8}\u{1F1FF}" },
  { code: "ET", name: "Ethiopia", flag: "\u{1F1EA}\u{1F1F9}" },
  { code: "FK", name: "Falkland Islands", flag: "\u{1F1EB}\u{1F1F0}" },
  { code: "FO", name: "Faroe Islands", flag: "\u{1F1EB}\u{1F1F4}" },
  { code: "FJ", name: "Fiji", flag: "\u{1F1EB}\u{1F1EF}" },
  { code: "FI", name: "Finland", flag: "\u{1F1EB}\u{1F1EE}" },
  { code: "FR", name: "France", flag: "\u{1F1EB}\u{1F1F7}" },
  { code: "GF", name: "French Guiana", flag: "\u{1F1EC}\u{1F1EB}" },
  { code: "PF", name: "French Polynesia", flag: "\u{1F1F5}\u{1F1EB}" },
  { code: "GA", name: "Gabon", flag: "\u{1F1EC}\u{1F1E6}" },
  { code: "GM", name: "Gambia", flag: "\u{1F1EC}\u{1F1F2}" },
  { code: "GE", name: "Georgia", flag: "\u{1F1EC}\u{1F1EA}" },
  { code: "DE", name: "Germany", flag: "\u{1F1E9}\u{1F1EA}" },
  { code: "GH", name: "Ghana", flag: "\u{1F1EC}\u{1F1ED}" },
  { code: "GI", name: "Gibraltar", flag: "\u{1F1EC}\u{1F1EE}" },
  { code: "GR", name: "Greece", flag: "\u{1F1EC}\u{1F1F7}" },
  { code: "GL", name: "Greenland", flag: "\u{1F1EC}\u{1F1F1}" },
  { code: "GD", name: "Grenada", flag: "\u{1F1EC}\u{1F1E9}" },
  { code: "GP", name: "Guadeloupe", flag: "\u{1F1EC}\u{1F1F5}" },
  { code: "GU", name: "Guam", flag: "\u{1F1EC}\u{1F1FA}" },
  { code: "GT", name: "Guatemala", flag: "\u{1F1EC}\u{1F1F9}" },
  { code: "GG", name: "Guernsey", flag: "\u{1F1EC}\u{1F1EC}" },
  { code: "GN", name: "Guinea", flag: "\u{1F1EC}\u{1F1F3}" },
  { code: "GW", name: "Guinea-Bissau", flag: "\u{1F1EC}\u{1F1FC}" },
  { code: "GY", name: "Guyana", flag: "\u{1F1EC}\u{1F1FE}" },
  { code: "HT", name: "Haiti", flag: "\u{1F1ED}\u{1F1F9}" },
  { code: "HN", name: "Honduras", flag: "\u{1F1ED}\u{1F1F3}" },
  { code: "HK", name: "Hong Kong", flag: "\u{1F1ED}\u{1F1F0}" },
  { code: "HU", name: "Hungary", flag: "\u{1F1ED}\u{1F1FA}" },
  { code: "IS", name: "Iceland", flag: "\u{1F1EE}\u{1F1F8}" },
  { code: "IN", name: "India", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "ID", name: "Indonesia", flag: "\u{1F1EE}\u{1F1E9}" },
  { code: "IR", name: "Iran", flag: "\u{1F1EE}\u{1F1F7}" },
  { code: "IQ", name: "Iraq", flag: "\u{1F1EE}\u{1F1F6}" },
  { code: "IE", name: "Ireland", flag: "\u{1F1EE}\u{1F1EA}" },
  { code: "IM", name: "Isle of Man", flag: "\u{1F1EE}\u{1F1F2}" },
  { code: "IL", name: "Israel", flag: "\u{1F1EE}\u{1F1F1}" },
  { code: "IT", name: "Italy", flag: "\u{1F1EE}\u{1F1F9}" },
  { code: "JM", name: "Jamaica", flag: "\u{1F1EF}\u{1F1F2}" },
  { code: "JP", name: "Japan", flag: "\u{1F1EF}\u{1F1F5}" },
  { code: "JE", name: "Jersey", flag: "\u{1F1EF}\u{1F1EA}" },
  { code: "JO", name: "Jordan", flag: "\u{1F1EF}\u{1F1F4}" },
  { code: "KZ", name: "Kazakhstan", flag: "\u{1F1F0}\u{1F1FF}" },
  { code: "KE", name: "Kenya", flag: "\u{1F1F0}\u{1F1EA}" },
  { code: "KI", name: "Kiribati", flag: "\u{1F1F0}\u{1F1EE}" },
  { code: "XK", name: "Kosovo", flag: "\u{1F1FD}\u{1F1F0}" },
  { code: "KW", name: "Kuwait", flag: "\u{1F1F0}\u{1F1FC}" },
  { code: "KG", name: "Kyrgyzstan", flag: "\u{1F1F0}\u{1F1EC}" },
  { code: "LA", name: "Laos", flag: "\u{1F1F1}\u{1F1E6}" },
  { code: "LV", name: "Latvia", flag: "\u{1F1F1}\u{1F1FB}" },
  { code: "LB", name: "Lebanon", flag: "\u{1F1F1}\u{1F1E7}" },
  { code: "LS", name: "Lesotho", flag: "\u{1F1F1}\u{1F1F8}" },
  { code: "LR", name: "Liberia", flag: "\u{1F1F1}\u{1F1F7}" },
  { code: "LY", name: "Libya", flag: "\u{1F1F1}\u{1F1FE}" },
  { code: "LI", name: "Liechtenstein", flag: "\u{1F1F1}\u{1F1EE}" },
  { code: "LT", name: "Lithuania", flag: "\u{1F1F1}\u{1F1F9}" },
  { code: "LU", name: "Luxembourg", flag: "\u{1F1F1}\u{1F1FA}" },
  { code: "MO", name: "Macao", flag: "\u{1F1F2}\u{1F1F4}" },
  { code: "MG", name: "Madagascar", flag: "\u{1F1F2}\u{1F1EC}" },
  { code: "MW", name: "Malawi", flag: "\u{1F1F2}\u{1F1FC}" },
  { code: "MY", name: "Malaysia", flag: "\u{1F1F2}\u{1F1FE}" },
  { code: "MV", name: "Maldives", flag: "\u{1F1F2}\u{1F1FB}" },
  { code: "ML", name: "Mali", flag: "\u{1F1F2}\u{1F1F1}" },
  { code: "MT", name: "Malta", flag: "\u{1F1F2}\u{1F1F9}" },
  { code: "MH", name: "Marshall Islands", flag: "\u{1F1F2}\u{1F1ED}" },
  { code: "MQ", name: "Martinique", flag: "\u{1F1F2}\u{1F1F6}" },
  { code: "MR", name: "Mauritania", flag: "\u{1F1F2}\u{1F1F7}" },
  { code: "MU", name: "Mauritius", flag: "\u{1F1F2}\u{1F1FA}" },
  { code: "YT", name: "Mayotte", flag: "\u{1F1FE}\u{1F1F9}" },
  { code: "MX", name: "Mexico", flag: "\u{1F1F2}\u{1F1FD}" },
  { code: "FM", name: "Micronesia", flag: "\u{1F1EB}\u{1F1F2}" },
  { code: "MD", name: "Moldova", flag: "\u{1F1F2}\u{1F1E9}" },
  { code: "MC", name: "Monaco", flag: "\u{1F1F2}\u{1F1E8}" },
  { code: "MN", name: "Mongolia", flag: "\u{1F1F2}\u{1F1F3}" },
  { code: "ME", name: "Montenegro", flag: "\u{1F1F2}\u{1F1EA}" },
  { code: "MS", name: "Montserrat", flag: "\u{1F1F2}\u{1F1F8}" },
  { code: "MA", name: "Morocco", flag: "\u{1F1F2}\u{1F1E6}" },
  { code: "MZ", name: "Mozambique", flag: "\u{1F1F2}\u{1F1FF}" },
  { code: "MM", name: "Myanmar", flag: "\u{1F1F2}\u{1F1F2}" },
  { code: "NA", name: "Namibia", flag: "\u{1F1F3}\u{1F1E6}" },
  { code: "NR", name: "Nauru", flag: "\u{1F1F3}\u{1F1F7}" },
  { code: "NP", name: "Nepal", flag: "\u{1F1F3}\u{1F1F5}" },
  { code: "NL", name: "Netherlands", flag: "\u{1F1F3}\u{1F1F1}" },
  { code: "NC", name: "New Caledonia", flag: "\u{1F1F3}\u{1F1E8}" },
  { code: "NZ", name: "New Zealand", flag: "\u{1F1F3}\u{1F1FF}" },
  { code: "NI", name: "Nicaragua", flag: "\u{1F1F3}\u{1F1EE}" },
  { code: "NE", name: "Niger", flag: "\u{1F1F3}\u{1F1EA}" },
  { code: "NG", name: "Nigeria", flag: "\u{1F1F3}\u{1F1EC}" },
  { code: "NU", name: "Niue", flag: "\u{1F1F3}\u{1F1FA}" },
  { code: "NF", name: "Norfolk Island", flag: "\u{1F1F3}\u{1F1EB}" },
  { code: "KP", name: "North Korea", flag: "\u{1F1F0}\u{1F1F5}" },
  { code: "MK", name: "North Macedonia", flag: "\u{1F1F2}\u{1F1F0}" },
  { code: "MP", name: "Northern Mariana Islands", flag: "\u{1F1F2}\u{1F1F5}" },
  { code: "NO", name: "Norway", flag: "\u{1F1F3}\u{1F1F4}" },
  { code: "OM", name: "Oman", flag: "\u{1F1F4}\u{1F1F2}" },
  { code: "PK", name: "Pakistan", flag: "\u{1F1F5}\u{1F1F0}" },
  { code: "PW", name: "Palau", flag: "\u{1F1F5}\u{1F1FC}" },
  { code: "PS", name: "Palestine", flag: "\u{1F1F5}\u{1F1F8}" },
  { code: "PA", name: "Panama", flag: "\u{1F1F5}\u{1F1E6}" },
  { code: "PG", name: "Papua New Guinea", flag: "\u{1F1F5}\u{1F1EC}" },
  { code: "PY", name: "Paraguay", flag: "\u{1F1F5}\u{1F1FE}" },
  { code: "PE", name: "Peru", flag: "\u{1F1F5}\u{1F1EA}" },
  { code: "PH", name: "Philippines", flag: "\u{1F1F5}\u{1F1ED}" },
  { code: "PL", name: "Poland", flag: "\u{1F1F5}\u{1F1F1}" },
  { code: "PT", name: "Portugal", flag: "\u{1F1F5}\u{1F1F9}" },
  { code: "PR", name: "Puerto Rico", flag: "\u{1F1F5}\u{1F1F7}" },
  { code: "QA", name: "Qatar", flag: "\u{1F1F6}\u{1F1E6}" },
  { code: "RO", name: "Romania", flag: "\u{1F1F7}\u{1F1F4}" },
  { code: "RU", name: "Russia", flag: "\u{1F1F7}\u{1F1FA}" },
  { code: "RW", name: "Rwanda", flag: "\u{1F1F7}\u{1F1FC}" },
  { code: "RE", name: "Reunion", flag: "\u{1F1F7}\u{1F1EA}" },
  { code: "BL", name: "Saint Barthelemy", flag: "\u{1F1E7}\u{1F1F1}" },
  { code: "SH", name: "Saint Helena", flag: "\u{1F1F8}\u{1F1ED}" },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "\u{1F1F0}\u{1F1F3}" },
  { code: "LC", name: "Saint Lucia", flag: "\u{1F1F1}\u{1F1E8}" },
  { code: "MF", name: "Saint Martin", flag: "\u{1F1F2}\u{1F1EB}" },
  { code: "PM", name: "Saint Pierre and Miquelon", flag: "\u{1F1F5}\u{1F1F2}" },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: "\u{1F1FB}\u{1F1E8}" },
  { code: "WS", name: "Samoa", flag: "\u{1F1FC}\u{1F1F8}" },
  { code: "SM", name: "San Marino", flag: "\u{1F1F8}\u{1F1F2}" },
  { code: "ST", name: "Sao Tome and Principe", flag: "\u{1F1F8}\u{1F1F9}" },
  { code: "SA", name: "Saudi Arabia", flag: "\u{1F1F8}\u{1F1E6}" },
  { code: "SN", name: "Senegal", flag: "\u{1F1F8}\u{1F1F3}" },
  { code: "RS", name: "Serbia", flag: "\u{1F1F7}\u{1F1F8}" },
  { code: "SC", name: "Seychelles", flag: "\u{1F1F8}\u{1F1E8}" },
  { code: "SL", name: "Sierra Leone", flag: "\u{1F1F8}\u{1F1F1}" },
  { code: "SG", name: "Singapore", flag: "\u{1F1F8}\u{1F1EC}" },
  { code: "SX", name: "Sint Maarten", flag: "\u{1F1F8}\u{1F1FD}" },
  { code: "SK", name: "Slovakia", flag: "\u{1F1F8}\u{1F1F0}" },
  { code: "SI", name: "Slovenia", flag: "\u{1F1F8}\u{1F1EE}" },
  { code: "SB", name: "Solomon Islands", flag: "\u{1F1F8}\u{1F1E7}" },
  { code: "SO", name: "Somalia", flag: "\u{1F1F8}\u{1F1F4}" },
  { code: "ZA", name: "South Africa", flag: "\u{1F1FF}\u{1F1E6}" },
  { code: "KR", name: "South Korea", flag: "\u{1F1F0}\u{1F1F7}" },
  { code: "SS", name: "South Sudan", flag: "\u{1F1F8}\u{1F1F8}" },
  { code: "ES", name: "Spain", flag: "\u{1F1EA}\u{1F1F8}" },
  { code: "LK", name: "Sri Lanka", flag: "\u{1F1F1}\u{1F1F0}" },
  { code: "SD", name: "Sudan", flag: "\u{1F1F8}\u{1F1E9}" },
  { code: "SR", name: "Suriname", flag: "\u{1F1F8}\u{1F1F7}" },
  { code: "SE", name: "Sweden", flag: "\u{1F1F8}\u{1F1EA}" },
  { code: "CH", name: "Switzerland", flag: "\u{1F1E8}\u{1F1ED}" },
  { code: "SY", name: "Syria", flag: "\u{1F1F8}\u{1F1FE}" },
  { code: "TW", name: "Taiwan", flag: "\u{1F1F9}\u{1F1FC}" },
  { code: "TJ", name: "Tajikistan", flag: "\u{1F1F9}\u{1F1EF}" },
  { code: "TZ", name: "Tanzania", flag: "\u{1F1F9}\u{1F1FF}" },
  { code: "TH", name: "Thailand", flag: "\u{1F1F9}\u{1F1ED}" },
  { code: "TL", name: "Timor-Leste", flag: "\u{1F1F9}\u{1F1F1}" },
  { code: "TG", name: "Togo", flag: "\u{1F1F9}\u{1F1EC}" },
  { code: "TK", name: "Tokelau", flag: "\u{1F1F9}\u{1F1F0}" },
  { code: "TO", name: "Tonga", flag: "\u{1F1F9}\u{1F1F4}" },
  { code: "TT", name: "Trinidad and Tobago", flag: "\u{1F1F9}\u{1F1F9}" },
  { code: "TN", name: "Tunisia", flag: "\u{1F1F9}\u{1F1F3}" },
  { code: "TR", name: "Turkey", flag: "\u{1F1F9}\u{1F1F7}" },
  { code: "TM", name: "Turkmenistan", flag: "\u{1F1F9}\u{1F1F2}" },
  { code: "TC", name: "Turks and Caicos Islands", flag: "\u{1F1F9}\u{1F1E8}" },
  { code: "TV", name: "Tuvalu", flag: "\u{1F1F9}\u{1F1FB}" },
  { code: "UG", name: "Uganda", flag: "\u{1F1FA}\u{1F1EC}" },
  { code: "UA", name: "Ukraine", flag: "\u{1F1FA}\u{1F1E6}" },
  { code: "AE", name: "United Arab Emirates", flag: "\u{1F1E6}\u{1F1EA}" },
  { code: "GB", name: "United Kingdom", flag: "\u{1F1EC}\u{1F1E7}" },
  { code: "US", name: "United States", flag: "\u{1F1FA}\u{1F1F8}" },
  { code: "VI", name: "US Virgin Islands", flag: "\u{1F1FB}\u{1F1EE}" },
  { code: "UY", name: "Uruguay", flag: "\u{1F1FA}\u{1F1FE}" },
  { code: "UZ", name: "Uzbekistan", flag: "\u{1F1FA}\u{1F1FF}" },
  { code: "VU", name: "Vanuatu", flag: "\u{1F1FB}\u{1F1FA}" },
  { code: "VA", name: "Vatican City", flag: "\u{1F1FB}\u{1F1E6}" },
  { code: "VE", name: "Venezuela", flag: "\u{1F1FB}\u{1F1EA}" },
  { code: "VN", name: "Vietnam", flag: "\u{1F1FB}\u{1F1F3}" },
  { code: "WF", name: "Wallis and Futuna", flag: "\u{1F1FC}\u{1F1EB}" },
  { code: "EH", name: "Western Sahara", flag: "\u{1F1EA}\u{1F1ED}" },
  { code: "YE", name: "Yemen", flag: "\u{1F1FE}\u{1F1EA}" },
  { code: "ZM", name: "Zambia", flag: "\u{1F1FF}\u{1F1F2}" },
  { code: "ZW", name: "Zimbabwe", flag: "\u{1F1FF}\u{1F1FC}" },
];

const countryMap = new Map(COUNTRIES.map((c) => [c.code, c]));

export function getCountryByCode(code: string): Country | undefined {
  return countryMap.get(code.toUpperCase());
}

export function getCountryName(code: string): string {
  return getCountryByCode(code)?.name ?? code;
}

export function formatLocation(
  countryCode: string | null,
  regionCode: string | null,
  regionName?: string
): string {
  if (!countryCode) return "";
  const countryName = getCountryName(countryCode);
  if (regionName) return `${regionName}, ${countryName}`;
  if (regionCode) return `${regionCode}, ${countryName}`;
  return countryName;
}
